os: osx
osx_image: xcode10.1
language: swift
xcode_workspace: JobTracker.xcworkspace
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
  - pod repo update
script:
  - xcodebuild build-for-testing -workspace JobTracker.xcworkspace -scheme JobTracker -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO  
