os: osx
osx_image: xcode10.1
language: swift
xcode_workspace: JobTracker.xcworkspace
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:i
  - gem install cocoapods --pre
  - pod install --repo-update
script:
  - xcodebuild -workspace JobTracker.xcworkspace -scheme JobTracker -sdk iphonesimulator12.1
